# Generated by Django 5.0.6 on 2024-05-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
